### ISSUE TITLE
[Compability stuff lmao] Compability with game maker sprite strips

### ISSUE THREAD

**Issue by bruhicantlogin** [rebane2001/WeirdM#6]
Idk if you can request compability and other things in here, but i think it would be cool to have compability with game maker sprite strips, i made a sprite strip animation and i really wanted to use it, but it doesn't seems to be working at all.

thanks for reading!

**Comment by rebane2001** [comment]
The site supports everything ffmpeg does. If you're using a file format not supported by ffmpeg then it's an obscure enough format that you should convert it to a more common format beforehand.

**Comment by bruhicantlogin** [comment]
ok, thanks for answering
anyways, how do you fix that thing were proccessing is stuck at 0%??? i use windows 10 64 bits and chrome.

**Comment by bruhicantlogin** [comment]
nvm i fixed it, Although the video just plays as a normal video, did discord fix the glitch? or is the exporting just not working at all?
